services:
  tarea-proyecto-devops:
     image: localhost:8082/tarea-proyecto-devops
     restart: always
     ports: 
      - "3001:3001"
     environment:
     - NODE_ENV=development
     - API_KEY=/run/secrets/api_file
secrets:
  api_file:
    file: api_file.txt

