services:
   backend:
     image: localhost:8082/tarea-proyecto-devops
     ports: 
        - "3000:3000"
     volumes:
       -  jenkins_home:/var/jenkins_home
     environment:
       NODE_ENV: development
       API_KEY: /run/secrets/db_password
     secrets:
       - db_password

secrets:
   db_password:
     file: my_secret.txt

volumes:
    db_data: