services:
 tarea-proyecto-devops:
      image: localhost:8082/tarea-proyecto-devops
      restart: always
      volumes:
        - my-volume:/path/in/container
      ports: 
        - "3000:3000"
      environment:
        NODE_ENV: development
        API_KEY: /run/secrets/my_secret 
      secrets:
        - my_secret

secrets:
    my_secret:
      file: my_secret.txt
volumes:
  my-volume:
    driver: local
    driver_opts:
      type: none
      device: /path/to/my-volume
      o: bind
    external: false
    labels:
      - "Volumen para mi servicio"
    name: my-volume
    scope: local