services:
  backend:
    image: localhost:8082/tarea-proyecto-devops
    restart: always
    volumes:
      - db-data:/etc/data
    ports: 
        - "3000:3000"
    environment:
      NODE_ENV: development

volumes:
  db-data: