services:
  tarea-proyecto-devops:
     image: localhost:8082/tarea-proyecto-devops
     restart: always
     ports: 
      - "3000:3000"
     environment:
      NODE_ENV: development
      API_KEY: /run/secrets/my_secret   
     secrets:
      - my_secret
secrets:
  my_secret:
    file: my_secret.txt
