services:
 tarea-proyecto-devops:
      image: localhost:8082/tarea-proyecto-devops
      restart: always
      volumes:
        - "vol2:/usr/share/"
      ports: 
        - "3000:3000"
      environment:
        NODE_ENV: development
        API_KEY: /run/secrets/my_secret 
      secrets:
        - my_secret

secrets:
    my_secret:
      file: my_secret.txt
volumes:
  vol2:
